name: RK

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  xcodeVersion: 11.0
  deploymentTarget:
    iOS: "14.0"

############
# Configs
############

configs:
  Debug: debug
  Release: release

packages:
  Swinject:
    url: https://github.com/Swinject/Swinject
    from: 2.5.0
  FirebaseAnalytics:
    url: https://github.com/firebase/firebase-ios-sdk
    branch: 6.34-spm-beta
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
  SkeletonUI:
    url: https://github.com/CSolanaM/SkeletonUI
#  RSwiftLibrary:
#    url: "https://github.com/mac-cain13/R.swift.Library"
############
# Targets
############

targets:
  RK:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "14.0"
    settings:
      base:
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: "ru.trykov.roskachestvo"
        CODE_SIGN_STYLE: "Manual"
        ENABLE_BITCODE: false
        DEVELOPMENT_TEAM: 7ZU2JEECEY
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: "apple-generic"
      configs:
        debug:
          CODE_SIGN_IDENTITY: "Apple Development: Created via API (744W5CQ5P7)"
          PROVISIONING_PROFILE_SPECIFIER: "match Development ru.trykov.roskachestvo"
        release:
          CODE_SIGN_IDENTITY: "iPhone Distribution: Юрий Трыков (7ZU2JEECEY)"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore ru.trykov.roskachestvo"
    sources:
      - path: RK
        excludes:
          - SupportingFiles/Info.plist
    dependencies:
      - package: Swinject
      - package: FirebaseAnalytics
      - package: Kingfisher
      - package: SkeletonUI
#      - package: Rswiftlibrary
    scheme:
      testTargets:
        - RKTests
      gatherCoverageData: true
    preBuildScripts:
      - script: "if which \"${PODS_ROOT}/SwiftLint/swiftlint\" >/dev/null; then\n\"${PODS_ROOT}/SwiftLint/swiftlint\" --strict\nelse\necho \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi\n"
        name: Swiftlint
      - script: "\"$PODS_ROOT/R.swift/rswift\" generate \"$SRCROOT/RK/Resources/Rswift/R.generated.swift\"\n"
        inputFiles: [ "$TEMP_DIR/rswift-lastrun" ]
        outputFiles: [ "$SRCROOT/RK/Resources/Rswift/R.generated.swift" ]
        name: R.swift
    info:
      path: RK/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "Роскачество+"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations: [ UIInterfaceOrientationPortrait ]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Light
        NSCameraUsageDescription: Приложение сможет отсканировать бар код для поиска продуктов
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIAppFonts: [ ProximaNovaBold.otf, Backpack-Bold.otf, Backpack-Light.otf, Backpack-Regular.otf ]
        LSRequiresIPhoneOS: true
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
  RKTests:
    type: bundle.unit-test
    platform: iOS
    sources: RKTests
    settings:
      base:
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: 7ZU2JEECEY
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/RK.app/RK
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - target: RK