name: RK

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  xcodeVersion: 11.0
  deploymentTarget:
    iOS: "13.0"

############
# Configs
############

configs:
  Debug: debug
  Release: release

############
# Targets
############

targets:
  RK:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 13.0
    settings:
      base:
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        PRODUCT_BUNDLE_IDENTIFIER: "ru.trykov.roskachestvo"
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_IDENTITY: ""
        ENABLE_BITCODE: false
        DEVELOPMENT_TEAM: 7ZU2JEECEY
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: "apple-generic"
      configs:
        debug:
          PROVISIONING_PROFILE_SPECIFIER: "match Development ru.trykov.roskachestvo"
        release:
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore ru.trykov.roskachestvo"
    sources:
      - path: RK
    preBuildScripts:
      - script: "if which \"${PODS_ROOT}/SwiftLint/swiftlint\" >/dev/null; then\n\"${PODS_ROOT}/SwiftLint/swiftlint\" --strict\nelse\necho \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi\n"
        name: Swiftlint
      - script: "\"$PODS_ROOT/R.swift/rswift\" generate \"$SRCROOT/RK/Resources/Rswift/R.generated.swift\"\n"
        inputFiles: ["$TEMP_DIR/rswift-lastrun"]
        outputFiles: ["$SRCROOT/RK/Resources/Rswift/R.generated.swift"]
        name: R.swift
    info:
      path: RK/SupportingFiles/Info.plist
      properties:
        CFBundleDisplayName: "Роскачество+"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Light
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIAppFonts: [ProximaNovaBold.otf, Backpack-Bold.otf, Backpack-Light.otf, Backpack-Regular.otf]
        LSRequiresIPhoneOS: true
        ITSAppUsesNonExemptEncryption: false
  RKTests:
    type: bundle.unit-test
    platform: iOS
    sources: RKTests
    settings:
      base:
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: 7ZU2JEECEY
        TEST_HOST: ""
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - target: RK