name: Swift

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: bundle install && bundle exec fastlane prepare
      - name: Certificates
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane certificates
      - name: Build
        run: bundle exec fastlane gym
      - name: Run tests
        run: bundle exec fastlane scan