name: Swift

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: bundle install && bundle exec fastlane prepare
      - name: Certificates
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane certificates
      - name: Build
        env:
          LOGIN_KEYCHAIN_PASSWORD: ${{ secrets.LOGIN_KEYCHAIN_PASSWORD }}
        run: bundle exec fastlane build_feature